### ISSUE TITLE
Data incompatible

### ISSUE THREAD

**Issue by floatrain** [dlorch/dnsserver#2]
In your main function, if multiple clients come to the server at the same time, you read the data in requestBytes for the first time. When the function handleDNSClients has not been copied, you read it again for the second time. Will you overwrite the data read for the first time.

**Comment by dlorch** [comment]
Hi @floatrain, well spotted, there is indeed a race condition there. I think the latest commit should fix it by moving the buffer local to the for loop, although I am not a 100% certain.
